/**
 * Mock 适配器的确定性示例数据
 * 取自原型（ai-english-learning-desktop）中 TED 文章
 * 《Inside the Mind of a Master Procrastinator》（Tim Urban）的展示数据：
 * 32 生词、8 短语、句级字幕示例、三题型智能出题
 * 结构稳定，可作测试夹具与后续页面的真实渲染数据源
 */
import type { PhraseEntry, Quiz, Sentence, WordEntry } from './types'

/** 32 个生词（词条顺序即单词预习页的默认顺序） */
export const MOCK_WORDS: WordEntry[] = [
  {
    word: 'procrastination',
    phonetic: '/prəˌkræstɪˈneɪʃən/',
    partOfSpeech: 'n.',
    definition: 'The act of delaying or postponing tasks',
    translation: '拖延症',
    example: 'His procrastination led to a last-minute panic.',
    synonyms: ['delay', 'postponement'],
  },
  {
    word: 'procrastinator',
    phonetic: '/prəˌkræstɪˈneɪtər/',
    partOfSpeech: 'n.',
    definition: 'A person who habitually delays tasks',
    translation: '拖延者',
    example: 'He calls himself a master procrastinator.',
    synonyms: ['delayer'],
  },
  {
    word: 'gratification',
    phonetic: '/ˌɡrætɪfɪˈkeɪʃən/',
    partOfSpeech: 'n.',
    definition: 'Pleasure or satisfaction obtained from an outcome',
    translation: '满足感',
    example: 'The monkey seeks instant gratification.',
    synonyms: ['satisfaction', 'pleasure'],
  },
  {
    word: 'rational',
    phonetic: '/ˈræʃənəl/',
    partOfSpeech: 'adj.',
    definition: 'Based on reason rather than emotion',
    translation: '理性的',
    example: 'The rational decision-maker plans for the long term.',
    synonyms: ['logical', 'reasonable'],
  },
  {
    word: 'deadline',
    phonetic: '/ˈdedlaɪn/',
    partOfSpeech: 'n.',
    definition: 'The latest time by which something must be done',
    translation: '截止日期',
    example: 'The Panic Monster awakens as the deadline approaches.',
    synonyms: ['due date', 'cutoff'],
  },
  {
    word: 'panic',
    phonetic: '/ˈpænɪk/',
    partOfSpeech: 'n.',
    definition: 'A sudden feeling of uncontrollable fear',
    translation: '恐慌',
    example: 'Panic set in the night before the due date.',
    synonyms: ['fear', 'alarm'],
  },
  {
    word: 'productivity',
    phonetic: '/ˌprɒdʌkˈtɪvəti/',
    partOfSpeech: 'n.',
    definition: 'The effectiveness of productive effort',
    translation: '生产力',
    example: 'Breaking tasks into chunks improved his productivity.',
    synonyms: ['efficiency', 'output'],
  },
  {
    word: 'conscious',
    phonetic: '/ˈkɒnʃəs/',
    partOfSpeech: 'adj.',
    definition: 'Deliberately aware of something',
    translation: '有意识的',
    example: 'He made a conscious effort to stop delaying.',
    synonyms: ['aware', 'deliberate'],
  },
  {
    word: 'landscape',
    phonetic: '/ˈlændskeɪp/',
    partOfSpeech: 'n.',
    definition: 'The overall shape or structure of something',
    translation: '全貌，格局',
    example: 'The landscape of his schedule changed after graduation.',
    synonyms: ['terrain', 'panorama'],
  },
  {
    word: 'thesis',
    phonetic: '/ˈθiːsɪs/',
    partOfSpeech: 'n.',
    definition: 'A long research paper written for a college degree',
    translation: '毕业论文',
    example: 'He spent months working on his senior thesis.',
    synonyms: ['dissertation'],
  },
  {
    word: 'graduate',
    phonetic: '/ˈɡrædʒueɪt/',
    partOfSpeech: 'v.',
    definition: 'To complete a course of study successfully',
    translation: '毕业',
    example: 'And he got it done, and he graduated.',
    synonyms: ['finish'],
  },
  {
    word: 'instant',
    phonetic: '/ˈɪnstənt/',
    partOfSpeech: 'adj.',
    definition: 'Happening or done immediately',
    translation: '即时的',
    example: 'The monkey lives entirely in the instant present.',
    synonyms: ['immediate', 'quick'],
  },
  {
    word: 'anxiety',
    phonetic: '/æŋˈzaɪəti/',
    partOfSpeech: 'n.',
    definition: 'A feeling of worry or unease',
    translation: '焦虑',
    example: 'Procrastination is not laziness, but the anxiety that builds over time.',
    synonyms: ['worry', 'unease'],
  },
  {
    word: 'overwhelm',
    phonetic: '/ˌəʊvərˈwelm/',
    partOfSpeech: 'v.',
    definition: 'To affect someone with a strong, unmanageable emotion',
    translation: '使不堪重负',
    example: 'He was overwhelmed by the size of the task.',
    synonyms: ['overpower'],
  },
  {
    word: 'motivation',
    phonetic: '/ˌməʊtɪˈveɪʃən/',
    partOfSpeech: 'n.',
    definition: 'The reason one has for acting in a certain way',
    translation: '动力',
    example: 'Deadlines turned out to be his only motivation.',
    synonyms: ['drive', 'incentive'],
  },
  {
    word: 'postpone',
    phonetic: '/pəʊstˈpəʊn/',
    partOfSpeech: 'v.',
    definition: 'To arrange for something to happen later than planned',
    translation: '推迟',
    example: 'He kept postponing the hardest task.',
    synonyms: ['delay', 'put off'],
  },
  {
    word: 'schedule',
    phonetic: '/ˈskedʒuːl/',
    partOfSpeech: 'n.',
    definition: 'A plan for when things will happen',
    translation: '日程表',
    example: 'The monkey ignores the schedule completely.',
    synonyms: ['timetable'],
  },
  {
    word: 'distraction',
    phonetic: '/dɪˈstrækʃən/',
    partOfSpeech: 'n.',
    definition: 'Something that prevents concentration',
    translation: '干扰，分心',
    example: 'The Internet is a giant distraction machine.',
    synonyms: ['diversion'],
  },
  {
    word: 'priority',
    phonetic: '/praɪˈɒrəti/',
    partOfSpeech: 'n.',
    definition: 'The state of being regarded as more important',
    translation: '优先事项',
    example: 'He finally made the thesis his top priority.',
    synonyms: ['precedence'],
  },
  {
    word: 'semester',
    phonetic: '/sɪˈmestər/',
    partOfSpeech: 'n.',
    definition: 'A half-year term in a school calendar',
    translation: '学期',
    example: 'His motivation faded at the start of the semester.',
    synonyms: ['term'],
  },
  {
    word: 'gradually',
    phonetic: '/ˈɡrædʒuəli/',
    partOfSpeech: 'adv.',
    definition: 'Slowly, by degrees',
    translation: '逐渐地',
    example: 'The anxiety gradually built as weeks passed.',
    synonyms: ['slowly'],
  },
  {
    word: 'suffer',
    phonetic: '/ˈsʌfər/',
    partOfSpeech: 'v.',
    definition: 'To experience something unpleasant',
    translation: '受苦，遭受',
    example: 'Even non-procrastinators suffer sometimes.',
    synonyms: ['endure'],
  },
  {
    word: 'phenomenon',
    phonetic: '/fəˈnɒmɪnən/',
    partOfSpeech: 'n.',
    definition: 'Something that exists and can be observed',
    translation: '现象',
    example: 'Procrastination is a universal phenomenon.',
    synonyms: ['occurrence'],
  },
  {
    word: 'spectator',
    phonetic: '/spekˈteɪtər/',
    partOfSpeech: 'n.',
    definition: 'One who watches instead of taking part',
    translation: '旁观者',
    example: 'He became a spectator of his own life.',
    synonyms: ['observer', 'onlooker'],
  },
  {
    word: 'strive',
    phonetic: '/straɪv/',
    partOfSpeech: 'v.',
    definition: 'To make a great effort toward something',
    translation: '努力，奋斗',
    example: 'Strive to shrink the monkey\u2019s territory bit by bit.',
    synonyms: ['struggle'],
  },
  {
    word: 'frenzy',
    phonetic: '/ˈfrenzi/',
    partOfSpeech: 'n.',
    definition: 'A state of uncontrolled activity',
    translation: '疯狂，狂热',
    example: 'The final week became a writing frenzy.',
    synonyms: ['madness'],
  },
  {
    word: 'culprit',
    phonetic: '/ˈkʌlprɪt/',
    partOfSpeech: 'n.',
    definition: 'The cause of a problem',
    translation: '罪魁祸首',
    example: 'The Instant Gratification Monkey is the main culprit.',
    synonyms: ['offender'],
  },
  {
    word: 'chore',
    phonetic: '/tʃɔːr/',
    partOfSpeech: 'n.',
    definition: 'A boring routine task',
    translation: '杂务，琐事',
    example: 'The monkey prefers fun over chores.',
    synonyms: ['task'],
  },
  {
    word: 'spiral',
    phonetic: '/ˈspaɪrəl/',
    partOfSpeech: 'n.',
    definition: 'A cycle that keeps getting worse',
    translation: '螺旋式恶化',
    example: 'He fell into a spiral of delay and guilt.',
    synonyms: ['cycle', 'whirl'],
  },
  {
    word: 'burst',
    phonetic: '/bɜːrst/',
    partOfSpeech: 'n.',
    definition: 'A short period of intense activity',
    translation: '爆发，一阵',
    example: 'The all-nighter was a frantic burst of work.',
    synonyms: ['spurt'],
  },
  {
    word: 'guilt',
    phonetic: '/ɡɪlt/',
    partOfSpeech: 'n.',
    definition: 'The bad feeling of having done something wrong',
    translation: '内疚',
    example: 'The dark playground is full of guilt.',
    synonyms: ['remorse'],
  },
  {
    word: 'resolve',
    phonetic: '/rɪˈzɒlv/',
    partOfSpeech: 'n.',
    definition: 'Firm determination to do something',
    translation: '决心',
    example: 'Her resolve to start early faded by noon.',
    synonyms: ['determination'],
  },
]

/** 8 个短语 */
export const MOCK_PHRASES: PhraseEntry[] = [
  {
    phrase: 'instant gratification',
    definition: 'The desire for immediate pleasure instead of a later reward',
    translation: '即时满足',
    example: 'The Instant Gratification Monkey cares only about instant gratification.',
  },
  {
    phrase: 'pull an all-nighter',
    definition: 'To stay awake all night to finish work',
    translation: '熬夜赶工',
    example: 'So finally, he decided to pull an all-nighter.',
  },
  {
    phrase: 'last-minute panic',
    definition: 'Anxiety caused by leaving things to the very end',
    translation: '最后一刻的慌乱',
    example: 'His procrastination led to a last-minute panic.',
  },
  {
    phrase: 'put off',
    definition: 'To delay doing something until later',
    translation: '推迟',
    example: 'He kept putting off the hardest task.',
  },
  {
    phrase: 'work on',
    definition: 'To spend time and effort doing a task',
    translation: '致力于',
    example: 'He had been working on his thesis for months.',
  },
  {
    phrase: 'break down into',
    definition: 'To divide something into smaller parts',
    translation: '分解成',
    example: 'Break the project down into small chunks.',
  },
  {
    phrase: 'calm down',
    definition: 'To become less excited or worried',
    translation: '冷静下来',
    example: 'Once the deadline passed, he finally calmed down.',
  },
  {
    phrase: 'let alone',
    definition: 'Used to emphasize that something is even less likely',
    translation: '更不用说',
    example: 'He hadn\u2019t read the abstract, let alone the whole thesis.',
  },
]

/** 句级分句与字幕示例（时间轴取自原型播客页，译文供逐句精听消费） */
export const MOCK_SENTENCES: Sentence[] = [
  {
    text: 'So I want to start with a story about a guy.',
    startMs: 0,
    endMs: 8000,
    translation: '那么我想先讲一个关于一个小伙子的故事。',
  },
  {
    text: 'He was a senior in college, and he was working on his thesis.',
    startMs: 8000,
    endMs: 20000,
    translation: '他当时是大四学生，正在写毕业论文。',
  },
  {
    text: 'And he had been working on it for months, and he just couldn\u2019t seem to finish it.',
    startMs: 20000,
    endMs: 35000,
    translation: '他已经写了好几个月，却好像怎么也写不完。',
  },
  {
    text: 'So finally, he decided to pull an all-nighter.',
    startMs: 35000,
    endMs: 45000,
    translation: '所以最后，他决定通宵赶工。',
  },
  {
    text: 'And he got it done, and he graduated.',
    startMs: 45000,
    endMs: 51000,
    translation: '他最终完成了论文，也顺利毕业了。',
  },
]

/**
 * 预设题库（两套轮换）：每次 generateQuiz 轮换取下一套，
 * 支撑「刷新题库」在 mock 下生成新题组。每套均含三题型。
 */
export const MOCK_QUIZZES_SETS: Quiz[][] = [
  [
    {
      type: 'single-choice',
      question: '文章作者认为拖延的核心原因是什么？',
      options: [
        '缺乏时间管理能力',
        '大脑存在即时满足与长期规划的冲突',
        '对任务难度的高估',
        '外界干扰过多',
      ],
      answer: '大脑存在即时满足与长期规划的冲突',
      explanation: '文章将拖延的根源描述为即时满足猴子与理性决策者之间的冲突。',
    },
    {
      type: 'fill-blank',
      question: '根据文章内容填空：The Instant Gratification Monkey cares only about ______.',
      answer: 'easy and fun',
      explanation: '即时满足猴子只关心 easy and fun（轻松与有趣）。',
    },
    {
      type: 'true-false',
      question: '判断正误：Panic Monster 只在截止日期临近时才会出现。',
      answer: false,
      explanation:
        '除截止日期临近外，公开出丑、职业灾难等可怕后果也会唤醒 Panic Monster，故该说法错误。',
    },
  ],
  [
    {
      type: 'single-choice',
      question: 'Panic Monster 在大脑里扮演什么角色？',
      options: [
        '帮助制定长期计划',
        '吓跑即时满足猴子，让理性决策者回到正轨',
        '提高任务的趣味性',
        '消除所有截止日期',
      ],
      answer: '吓跑即时满足猴子，让理性决策者回到正轨',
      explanation: 'Panic Monster 是唯一能让即时满足猴子害怕的存在，它出现时猴子会逃走。',
    },
    {
      type: 'fill-blank',
      question: '根据文章内容填空：The ______ is the only thing that scares the Instant Gratification Monkey.',
      answer: 'Panic Monster',
      explanation: '文中说明 Panic Monster 是唯一能吓跑即时满足猴子的存在。',
    },
    {
      type: 'true-false',
      question: '判断正误：作者认为只有“拖延症患者”才会拖延。',
      answer: false,
      explanation: '作者结尾指出每个人的大脑里都住着即时满足猴子，人人都会在某些事情上拖延。',
    },
  ],
]
